networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #I created network already using docker network create roboshop
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
    image: maheswari450/mongodb-optimize:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: maheswari450/catalogue-optimize:v1
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    image: maheswari450/frontend-optimize:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - catalogue